#!/bin/bash

export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_CTRL_R_OPTS="--preview 'echo {}' \
    --preview-window down:3:hidden:wrap \
    --bind '?:toggle-preview'"

# TODO find a way to use this in fzf preview
_preview_file() {
    bat --color=always $1
}

eg() {
    RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
    query=$1
    selected=($(FZF_DEFAULT_COMMAND="$RG_PREFIX '$query'" \
      fzf --bind="change:reload:$RG_PREFIX {q} || true" \
          --ansi --disabled --query "$query" \
          --height=60% --layout=reverse \
          --preview 'fzf_preview.sh {}'))
          #--preview "bat --color=always $(awk -F: '{print $1}' {})"))
    read -r file line <<<$(awk -F: '{print $1, $2}' <<<$selected)
    if [[ -n $file ]]
    then
        vim $file +$line
    fi
}

ef() {
    RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
    query=$1
    file=($(fzf --ansi \
          --height=60% --layout=reverse \
          --preview "fzf_preview.sh {}"))
    if [[ -n $file ]]
    then
        vim $file
    fi
}
